### PR TITLE
added a landing page

### PR DESCRIPTION
**Pull request by skhilton**
This PR creates a landing page for the dms-view links. This is simply a markdown file which is converted into html and has a nested URL. 

Here is what the landing page currently looks like (it would live at the URL https://jbloomlab.github.io/SARS-CoV-2-RBD-DMS/structures)
image

Next steps before this PR is merged 
1. (necessary) the dms-view links need to be added and maybe the wording changed? This can be done by editing the markdown file `structures.md`
2. (not necessary but maybe nice) restructure the website slightly. Have jbloomlab.github.io/SARS-CoV-2-RBD-DMS be a landing page with links to either jbloomlab.github.io/SARS-CoV-2-RBD-DMS/heatmaps or jbloomlab.github.io/SARS-CoV-2-RBD-DMS/structures. This will necessitate updating the links to the heatmaps in the manuscript and in other places. Alternatively, adding a link from the interactive heatmaps to this dms-view landing page. I can handle this step if you tell me your preference.

### CODE REVIEW

**Comment by tylernstarr** [comment]
dms-view links are added in the structures.md file!

**Comment by jbloom** [comment]
@tylernstarr @skhilton:

I think this is a nice setup. 

I'm adding a list of things that I think should be updated here before merging.

- I like this current setup, I just think the main page can be heatmap and the instructions for that should also include mention of link to this. So URLs stay the same.

- Markdown summary for actual `dms-view`:

  - The word "data" is plural, so should be "What data **are** shown here?"
  - I think the whole summary format of providing the entire paper title in huge font, followed by authors, followed by abstract takes up a lot of space before it gets to the point. I would suggest leading the summary with a succinct description of what is actually shown: the DMS data on the ACE2 bound RBD from SARS-CoV-2. Then just have links to the paper for more information on the experiments, and the stuff about what the various metrics mean.

  - For the description of the site metrics, you might just include simple explanations as well such as higher entropy means more tolerant to mutations, etc.

- Landing pad page: I think it would be helpful to spend less time saying `dms-view` and more text with a plain language English summary of what the links actually show: interactive visualizations of the deep mutational scanning data on the protein structure. The landing page should probably definitely have a link to the paper.

- @skhilton, maybe this cannot be programmed into the HTML, but is it possible to set up the landing pad so that each link opens in a new tab since the *back* button doesn't work with `dms-view`? 

- @tylernstarr , do you want to add more additional links to specific pre-formed views with short descriptions? Maybe not necessary, but a possibility. Certainly you could imagine views that highlight different sets of important sites if you think this is useful.

**Comment by skhilton** [comment]
@jbloom, @tylernstarr: sounds good! Yes, we can have the links open in a new tab but this involves replacing the markdown syntax for links (`[something](link-to-something)`) with some gross looking html. So, it probably makes more sense for @tylernstarr to get the markdown structures page looking the way he wants and then I can go back in and change the links.

To bring in a comment mentioned in the google doc, you can definitely have links for each panel or view of a figure. For instances, here I recapitulated each panel of Juhye's paper: https://dms-view.github.io/docs/lee2019mapping/

**Comment by skhilton** [comment]
I realized I don't know the timeline for submission and I am at an interview all day tomorrow. Here is an example of the html you need to have the links open in a new tab: https://raw.githubusercontent.com/dms-view/docs/master/lee2019mapping.md

I am still more than happy to do it if I am free but I don't want to hold anything up.

**Comment by jbloom** [comment]
Thanks @skhilton. I agree with basic strategy of letting @tylernstarr firm up links, and then I can make links open in new browser in way you suggest.

**Comment by tylernstarr** [comment]
Alright @jbloom, I addressed all of the tweaks across the dms-view landing pad, adding the link to dms-view in the interactive heatmap display, and updating the md annotations on the dms-view displays. Should be ready to format the links if you are able, and merge

**Comment by skhilton** [comment]
@tylernstarr @jbloom: I have some time, I can do this right now

**Comment by skhilton** [comment]
@tylernstarr: You can merge now. 

I confirmed that all of the links work and I think I can tell that they are the correct residues (meaning I didn't mess up copy paste) for everything except for the antibody epitopes. If you could spot check those before (or after) the merge that would be great. 

After you merge, I will also make sure that everything looks good on GitHub pages like it does on my local build

**Pull request merged**
